// test-sveltekit/src/components/UserMenu.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { useAuth } from '@convex-dev/auth/sveltekit';
	
	export let username: string;
	
	const { signOut } = useAuth();
	
	async function handleSignOut() {
		await signOut();
		goto('/');
	}
</script>

<div class="flex items-center gap-2 text-sm font-medium">
	{username}
	<div class="dropdown dropdown-end">
		<button class="btn btn-sm variant-filled-surface rounded-full" aria-label="user menu">
			<span class="h-5 w-5">👤</span>
			<span class="sr-only">Toggle user menu</span>
		</button>
		<div class="dropdown-menu variant-filled-surface">
			<div class="menu-item-label">{username}</div>
			<div class="menu-item-divider"></div>
			<button class="menu-item" on:click={handleSignOut}>Sign out</button>
		</div>
	</div>
</div>

// test-nextjs/components/UserMenu.tsx
"use client";

import { ThemeToggle } from "@/components/ThemeToggle";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useAuthActions } from "@convex-dev/auth/react";
import { PersonIcon } from "@radix-ui/react-icons";
import { useRouter } from "next/navigation";
import { ReactNode } from "react";

export function UserMenu({ children }: { children: ReactNode }) {
  return (
    <div className="flex items-center gap-2 text-sm font-medium">
      {children}
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button
            variant="secondary"
            size="icon"
            className="rounded-full"
            aria-label="user menu"
          >
            <PersonIcon className="h-5 w-5" />
            <span className="sr-only">Toggle user menu</span>
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuLabel>{children}</DropdownMenuLabel>
          <DropdownMenuSeparator />
          <DropdownMenuLabel className="flex items-center gap-2 py-0 font-normal">
            Theme
            <ThemeToggle />
          </DropdownMenuLabel>
          <SignOutButton />
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}

function SignOutButton() {
  const { signOut } = useAuthActions();
  const router = useRouter();
  return (
    <DropdownMenuItem
      onClick={() => void signOut().then(() => router.push("/"))}
    >
      Sign out
    </DropdownMenuItem>
  );
}
