// test-sveltekit/src/lib/Chat/Chat.svelte
<script lang="ts">
	import { useQuery, useConvexClient } from 'convex-svelte';
	import { api } from '$lib/convex/_generated/api';
	import type { Id } from '$lib/convex/_generated/dataModel';
	import Message from './Message.svelte';
	import MessageList from './MessageList.svelte';
	
	interface Props {
		viewer: Id<'users'>;
	}

	let { viewer }: Props = $props();

	const client = useConvexClient();
	
	let newMessageText = $state('');
	
	const messages = useQuery(api.messages.list, {});
	
	async function handleSubmit(event: Event) {
		event.preventDefault();
		if (newMessageText.trim() === '') return;
		
		try {
			await client.mutation(api.messages.send, { body: newMessageText });
			newMessageText = '';
		} catch (error) {
			console.error('Failed to send message:', error);
		}
	}
</script>

<MessageList messages={messages.data}>
	{#if messages.data}
		{#each messages.data as message}
			<Message
				authorName={message.author}
				authorId={message.userId}
				viewerId={viewer}
			>
				{message.body}
			</Message>
		{/each}
	{/if}
</MessageList>

<div class="border-t">
	<form onsubmit={handleSubmit} class="flex gap-2 p-4">
		<input 
			type="text"
			bind:value={newMessageText}
			placeholder="Write a message…"
			class="input"
		/>
		<button 
			type="submit" 
			disabled={newMessageText === ''}
			class="btn preset-filled-pri"
		>
			Send
		</button>
	</form>
</div>

// test-nextjs/app/product/Chat/Chat.tsx
"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { api } from "@/convex/_generated/api";
import { Id } from "@/convex/_generated/dataModel";
import { useMutation, useQuery } from "convex/react";
import { FormEvent, useState } from "react";
import { Message } from "./Message";
import { MessageList } from "./MessageList";

export function Chat({ viewer }: { viewer: Id<"users"> }) {
  const [newMessageText, setNewMessageText] = useState("");
  const messages = useQuery(api.messages.list);
  const sendMessage = useMutation(api.messages.send);

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    sendMessage({ body: newMessageText })
      .then(() => {
        setNewMessageText("");
      })
      .catch((error) => {
        console.error("Failed to send message:", error);
      });
  };

  return (
    <>
      <MessageList messages={messages}>
        {messages?.map((message) => (
          <Message
            key={message._id}
            authorName={message.author}
            authorId={message.userId}
            viewerId={viewer}
          >
            {message.body}
          </Message>
        ))}
      </MessageList>
      <div className="border-t">
        <form onSubmit={handleSubmit} className="flex gap-2 p-4">
          <Input
            value={newMessageText}
            onChange={(event) => setNewMessageText(event.target.value)}
            placeholder="Write a message…"
          />
          <Button type="submit" disabled={newMessageText === ""}>
            Send
          </Button>
        </form>
      </div>
    </>
  );
}
