// test-nextjs/app/(authed)/product/Chat/MessageList.tsx
import { ReactNode, useEffect, useRef } from "react";

export function MessageList({
  messages,
  children,
}: {
  messages: unknown;
  children: ReactNode;
}) {
  const messageListRef = useRef<HTMLOListElement>(null);

  // Scrolls the list down when new messages
  // are received or sent.
  useEffect(() => {
    if (messageListRef.current) {
      messageListRef.current.scrollTo({
        top: messageListRef.current.scrollHeight,
        behavior: "smooth",
      });
    }
  }, [messages]);
  return (
    <ol
      ref={messageListRef}
      className="flex grow flex-col gap-4 overflow-y-auto scroll-smooth px-8 py-4"
    >
      {children}
    </ol>
  );
}

// test-sveltekit/src/routes/product/Chat/MessageList.svelte
<script lang="ts">
	interface Props {
		messages: unknown;
		children?: import('svelte').Snippet;
	}

	let { messages, children }: Props = $props();
	let listEl: HTMLOListElement;

	$effect(() => {
		messages;

		if (listEl) {
			listEl.scrollTo({
				top: listEl.scrollHeight,
				behavior: 'smooth'
			});
		}
	});
</script>

<ol bind:this={listEl} class="flex grow flex-col gap-4 overflow-y-auto scroll-smooth px-8 py-4">
	{@render children?.()}
</ol>
